name: volante
description: "Testes para o Volante"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.26.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  provider: ^6.1.1
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.7
  cloud_firestore: ^4.15.6
  google_maps: ^7.0.0
  flutter_svg: ^2.0.10+1
  flutter_polyline_points_plus: ^3.0.0
  location: ^5.0.3
  google_maps_flutter: ^2.2.8
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.png
    - assets/images/bandeira.png
    - assets/images/localizacao.png
    - assets/images/splash.png
    - assets/icons/avatar.bmp
    - assets/icons/localizacao.bmp
    - assets/icons/bandeira.bmp