// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBspgwjPfztZc6NdsRyOwpLKXem99TpvO0',
    appId: '1:1013078136393:web:5960dada973735df4bd198',
    messagingSenderId: '1013078136393',
    projectId: 'volante-19782024',
    authDomain: 'volante-19782024.firebaseapp.com',
    storageBucket: 'volante-19782024.appspot.com',
    measurementId: 'G-LRNZ8GF2XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnksjZLRwXPm34YHoDozCYEXQHEfzFsyU',
    appId: '1:1013078136393:android:f41dd33f674f7bbb4bd198',
    messagingSenderId: '1013078136393',
    projectId: 'volante-19782024',
    storageBucket: 'volante-19782024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDAvpZnfHSMq_vgLpJibSSi4NXYEAqpbc',
    appId: '1:1013078136393:ios:52eca03ec47fc6734bd198',
    messagingSenderId: '1013078136393',
    projectId: 'volante-19782024',
    storageBucket: 'volante-19782024.appspot.com',
    iosBundleId: 'com.example.volante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDAvpZnfHSMq_vgLpJibSSi4NXYEAqpbc',
    appId: '1:1013078136393:ios:7b3658dba1cb5ecc4bd198',
    messagingSenderId: '1013078136393',
    projectId: 'volante-19782024',
    storageBucket: 'volante-19782024.appspot.com',
    iosBundleId: 'com.example.volante.RunnerTests',
  );
}
